### ISSUE TITLE
Expired Listing Filter

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1799]
The Listings Tab in the Sell-Menu doesn't filter for expired listings. At least in my case no expired listings were found. Active (published) listings filter was ok.
Additionally I would prefer to change the order when sorting "By Creation" (beginning with the latest one from top, and the oldest one on bottom)

**Comment by zaSmilingIdiot** [comment]
Nice. Has been fixed in the UI. Should be available in the next release.

**Comment by kangoala** [comment]
This is still an issue with latest v3.0.0-RC-test005 release.
(At least on my installation)

**Comment by zaSmilingIdiot** [comment]
Will take a look into this again...

**Comment by zaSmilingIdiot** [comment]
Embarrassingly, it seems like an update to the change to fix this originally  was not merged in. The change has been made and should now properly work in the next release :)
Apologies for this.

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
