### ISSUE TITLE
After a while no more item downloads

### ISSUE THREAD

**Issue by mahdi-ln** [particl/particl-desktop#1823]
**Describe the bug**
In marketplace after a while no more item downloads. Even reopening app doesn't solve problem

**Screenshots**
![image](https://user-images.githubusercontent.com/27496531/140624652-a1948fec-ba7b-4854-a379-92fee7c2eea5.png)

OS: Manjaro 21.1

**Comment by mahdi-ln** [comment]
[market.log](https://github.com/particl/particl-desktop/files/7491298/market.log)

**Comment by zaSmilingIdiot** [comment]
That time-offset appears to be an issue. Best to start by resolving that: this may require you to ensure that your OS/system clock is properly synced. Once this is done then we can proceed to troubleshoot further if the issue is ongoing.

**Comment by zaSmilingIdiot** [comment]
@mahdi-ln Have you managed to resolve this issue, or is it still a problem?

**Comment by mahdi-ln** [comment]
> @mahdi-ln Have you managed to resolve this issue, or is it still a problem?

I can't test more later versions because of https://github.com/particl/particl-desktop/issues/1831

**Comment by mahdi-ln** [comment]
It is still problem
Version 3.2 fresh install on windows

![image](https://user-images.githubusercontent.com/27496531/169704652-9420719d-dab2-4c00-89e7-7ed8b2642935.png)

**Comment by zaSmilingIdiot** [comment]
Should be resolved as from the release of https://github.com/zaSmilingIdiot/particl-market/releases/tag/v0.3.11
Has been included in Particl Desktop, see https://github.com/particl/particl-desktop/commit/7a9b4049d46c1a68a8177fe0bf3dafe08786502c
Will be available in Particl Desktop v3.2.2, which should be available within the next few hours.

**Comment by mahdi-ln** [comment]
I'm sure it is not solved.

![image](https://user-images.githubusercontent.com/27496531/185521666-71e80283-8607-430c-af22-7eb5c028b424.png)

**Comment by zaSmilingIdiot** [comment]
How are you determining that there are newer items available, or more items that are not downloaded?

I'll happily re-open the issue if its not properly resolved, but a screenshot doesn't tell me much in terms of troubleshooting:
1. what are expecting to see vs what you are currently seeing, and 
2. how are you determining what you are expecting to see is accurate?
